# Generated by Django 4.2.17 on 2024-12-16 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officestaff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('borrowed_date', models.DateField(auto_now_add=True, verbose_name='Borrowed Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Returned Date')),
                ('status', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned')], default='BORROWED', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='library_history', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Library Borrowing Record',
                'verbose_name_plural': 'Library Borrowing Records',
                'ordering': ['-borrowed_date'],
            },
        ),
    ]
