# Generated by Django 4.2.17 on 2024-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('officestaff', 'Office Staff'), ('librarian', 'Librarian')], default='officestaff', max_length=20),
        ),
    ]
