# Generated by Django 4.2.17 on 2024-12-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('officestaff', 'Office Staff'), ('librarian', 'Librarian')], default='officestaff', max_length=20),
        ),
        migrations.CreateModel(
            name='FeesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of fees paid.', max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True, help_text='The date when the fees were paid.')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID for online or card payments.', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional details or remarks about the payment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='The user who paid the fees.', on_delete=django.db.models.deletion.CASCADE, related_name='fees_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
