# Generated by Django 4.2.17 on 2024-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_employee_id_user_user_id_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('officestaff', 'Office Staff'), ('librarian', 'Librarian')], max_length=20),
        ),
        migrations.DeleteModel(
            name='FeesHistory',
        ),
    ]
